services:
  postgres:
    image: postgres:latest
    container_name: kiril
    environment:
      POSTGRES_DB: kiril_bot
      POSTGRES_USER: dok2412
      POSTGRES_PASSWORD: 1p2o3i4u5y
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=50'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    ports:
      - "5464:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U dok2412 -d kiril_bot' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: src1
      dockerfile: Dockerfile
    container_name: kiril_bot
    restart: always
    ports:
      - '8081:8081'
    environment:
      PSQL_DB_USER: dok2412
      PSQL_DB_PASSWORD: 1p2o3i4u5y
      PSQL_DB_HOST: kiril
      PSQL_DB_PORT: 5432
      PSQL_DB_NAME: kiril_bot
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge